### ISSUE TITLE
OBEX implementation

### ISSUE THREAD

**Issue by sireliah** [szeged/blurz#18]
Hej! This is not really an issue, but rather a suggestion of a new feature in the library, that I would like to implement. I was thinking about writing support for OBEX protocol, as specified here:

https://github.com/wolfeidau/bluez/blob/master/doc/obex-api.txt

I'm using your library for my own small project and I already implemented part of OBEX API:
- creating the session
- starting the file transfer (ObjectPush1)
- waiting until the transfer is completed

https://github.com/sireliah/dragit/blob/master/src/bluetooth/obex.rs

Of course I would write more sustainable code. :smiley: 
What do you think about this idea in general? Does it make sense to include OBEX?

**Comment by sireliah** [comment]
@dati91 @zakorgy ?

**Comment by dati91** [comment]
Hi!

Sorry for the late response.
First of all, just to clarify things. The main reason this repository exists is that back in 2016 we needed a Bluetooth Low Energy (BLE) implementation in rust and there was no lib back then.
Since then, we moved on to other projects and we don't have the time to work on it anymore.

Feel free to send a PR! (but things could become a little bit complicated ([like here](https://github.com/szeged/blurz/pull/13)) since it is part of Servo)

The main thing is not introducing API breaking changes (or if needed handling them in the other repos as well). To be honest I'm not familiar with the OBEX API, but if it can use our current API and extend it, then it will be just fine.

What I can contribute to this whole thing is look trough your PR, but (most probably) I won't be able to try it, so I will have to trust you on that one.

Let me know what you think.

**Comment by sireliah** [comment]
Thanks for your answer!

I saw the that PR with the API updates and I'm not planning to introduce any radical changes. My intent is to extend usability of the library to provide out-of-box support for sending files and managing file transfers. OBEX does it and fortunately there is no need to implement it on the low level. It is sufficient to use the D-Bus for all communication.

However I didn't know that this library joined the Servo. I'm not sure if Servo ever needs OBEX implementation (and I don't know if I'd dare to contribute to Servo), but I guess we can think about this later. 

My plan is to start with Linux and write support for basic OBEX operations. Docs and tests included.

Anyway, thanks for encouraging answer. I'll write part of the implementation and let you know. :+1:

**Comment by dati91** [comment]
Please reopen if you think this is still relevant.
Closing reason: #20
